title: "Michael Berthold"
description: "Portfolio website of Michael Berthold"

url: "https://lacahelpme.github.io"
baseurl: "/test"

markdown: kramdown
permalink: pretty
plugins: []

default_lang: en
languages:
  - en
  - de
